# Site settings

author: neobradley
email: vic.william2005@gmail.com
github_username:  neobradley
linkedin_username: yuyu-lai-479a00120
facebook_username: tajg2011
#twitter_username: ryxstephen2010

head-title: neobradley blog
title: neobradley blog

baseurl: "/neobradley.github.io"    # the subpath of your site, "/blog"
url: "https://neobradley.github.io"

# footer 
description: "如果沒能一次成功，那就叫它 1.0 版吧！"

favo: "略懂略懂"
descrpt: "“學而時習之，不亦樂乎”  ——《論語》"

#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 15
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]

#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
# Icon
# All mdi icon, see: https://materialdesignicons.com/
header-color: "grey darken-4"
head-theme-color: "#212121"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "grey darken-4"
footer-button-color: "blue-grey darken-4"
footer-link-color: "green-text text-accent-1"

share-button-color: "teal"
share-button-small-color: "teal"

##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

